# Generated by Django 6.0 on 2026-05-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="disponible",
            field=models.BooleanField(default=True),
        ),
    ]
